---
version: '2.0'
services:
  base:
    build:
      context: .
    volumes:
      - "$HOME/.aws:/root/.aws"
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2

  shush:
    extends:
      service: base
    entrypoint:
      - shush
