---
base:
  build: .
  # image: my-shush
  volumes:
    - "$HOME/.aws:/root/.aws"
  environment:
    AWS_DEFAULT_REGION: ap-southeast-2

shush:
  extends:
    service: base
  # image:
  #   my-shush
  entrypoint:
    - shush
